# Generated by Django 6.1.1 on 2026-09-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_data',
            field=models.TextField(blank=True, help_text='Persistent base64 data URI fallback for ephemeral hosting like Render', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture_data',
            field=models.TextField(blank=True, help_text='Persistent base64 data URI fallback for ephemeral hosting like Render', null=True),
        ),
    ]
